kind: Deployment
apiVersion: apps/v1

metadata:
  namespace: {{ .Values.nameSpace }}
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.serviceaccount.ingeress.controller }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - --entrypoints.web.address=:8000
            - --entrypoints.admin.address=:8080
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 8000
            - name: admin
              containerPort: 8080