sensor:
    solar_panels_total_power:
      unique_id: "total_solar_power"
      friendly_name: "Total Solar Power"
      unit_of_measurement: "kW"
      value_template: >
        {{ (
           states('sensor.solar_panel_501000014054_4_power')|float(default=0) +
           states('sensor.solar_panel_501000014191_1_power')|float(default=0) +
           states('sensor.solar_panel_501000025147_2_power')|float(default=0) +
           states('sensor.solar_panel_501000014054_2_power')|float(default=0) +
           states('sensor.solar_panel_501000014043_2_power')|float(default=0) +
           states('sensor.solar_panel_501000014031_2_power')|float(default=0) +
           states('sensor.solar_panel_501000014031_3_power')|float(default=0) +
           states('sensor.solar_panel_501000014191_4_power')|float(default=0) +
           states('sensor.solar_panel_501000014031_4_power')|float(default=0) +
           states('sensor.solar_panel_501000014043_4_power')|float(default=0) +
           states('sensor.solar_panel_501000014191_3_power')|float(default=0) +
           states('sensor.solar_panel_501000014191_2_power')|float(default=0) +
           states('sensor.solar_panel_501000025147_1_power')|float(default=0) +
           states('sensor.solar_panel_501000014054_1_power')|float(default=0) +
           states('sensor.solar_panel_501000019070_2_power')|float(default=0) +
           states('sensor.solar_panel_501000014043_1_power')|float(default=0) +
           states('sensor.solar_panel_501000025147_4_power')|float(default=0) +
           states('sensor.solar_panel_501000019070_1_power')|float(default=0) +
           states('sensor.solar_panel_501000014031_1_power')|float(default=0) +
           states('sensor.solar_panel_501000014043_3_power')|float(default=0) +
           states('sensor.solar_panel_501000025147_3_power')|float(default=0) +
           states('sensor.solar_panel_501000014054_3_power')|float(default=0) +
           states('sensor.solar_panel_501000019070_4_power')|float(default=0) +
           states('sensor.solar_panel_501000019070_3_power')|float(default=0)
        ) | float * 0,001 }}