kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-path-pvc
  namespace: {{ .Values.nameSpace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi