kind: Deployment
apiVersion: apps/v1

metadata:
  name: ubuntu
  namespace: tools
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:noble
          command: [ "tail", "-f", "/dev/null" ]
