kind: IngressRouteTCP
apiVersion: traefik.io/v1alpha1

metadata:
  name: {{ .Values.appName }}-tcp
  namespace: {{ .Values.nameSpace }}
spec:
  entryPoints:
    - {{ .Values.ingress.tcp.entryPoint | quote }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ .Values.appName }}
          port: openvpn-tcp
