kind: Service
apiVersion: v1

metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - name: openvpn-udp
      port: {{ .Values.container.portUDP }}
      protocol: UDP
      targetPort: {{ .Values.container.portUDP }}
    - name: admin
      port: {{ .Values.container.portAdmin }}
      protocol: TCP
      targetPort: {{ .Values.container.portAdmin }}
