argo-cd:
  nameOverride: argocd
  fullnameOverride: argocd
  namespaceOverride: argo-cd

  global:
    domain: argocd.local

  configs:
    params:
      server.insecure: true
    repositories:
      raspberry-home-assistant:
        url: https://github.com/kad-bloemgx/raspberry_home-assistant.git
        type: git

  extraObjects:
    - apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      metadata:
        name: raspberry-home-assistant-apps
        namespace: argo-cd
      spec:
        generators:
          - git:
              repoURL: https://github.com/kad-bloemgx/raspberry_home-assistant.git
              revision: HEAD
              directories:
                - path: deploy/helm/argocd/*
        template:
          metadata:
            name: "{{`{{path.basename}}`}}"
            namespace: argo-cd
          spec:
            project: default
            source:
              repoURL: https://github.com/kad-bloemgx/raspberry_home-assistant.git
              targetRevision: HEAD
              path: "{{`{{path}}`}}"
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{`{{path.basename}}`}}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

  server:
    ingress:
      enabled: false

ingress:
  enabled: true
  host: argocd.gerardbloemendaal.freemyip.com
