kind: Service
apiVersion: v1

metadata:
  name: openvpn
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: NodePort
  ports:
    - naem: openvpn
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 33051