kind: Service
apiVersion: v1

metadata:
  name: openvpn-admin
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: NodePort
  ports:
    - name: openvpn-adm
      port: 943
      protocol: TCP
      targetPort: 943
      nodePort: 30050