kind: IngressRoute
apiVersion: traefik.io/v1alpha1

metadata:
  name: unifi-webui
  namespace: {{ .Values.nameSpace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`unifi.lokaal`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: unifi-os-server-webui-svc
          port: 80

---

kind: IngressRoute
apiVersion: traefik.io/v1alpha1

metadata:
  name: unifi-rtp
  namespace: {{ .Values.nameSpace }}
spec:
  entryPoints:
    - rtp
  routes:
      services:
        - name: unifi-os-server-rtp-svc
          port: 5005