apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-server-pvc
  namespace: {{ .Values.nameSpace }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi