replicaCount: 1

appName: home-assistant
nameSpace: home-assistant

image:
  repository: homeassistant/home-assistant
  tag: "2026.9"

container:
  port: 8123

persistence:
  storageClass: local-path-retain
  size: 10Gi

externalHost: home-assistant.gerardbloemendaal.freemyip.com

coiot:
  enabled: true
  nodePort: 30037

