apiVersion: v2
name: traefik
description: Traefik deployment chart managed by Argo CD

type: application
version: 1.0.14
appVersion: "v3.7.0"

dependencies:
  - name: traefik
    version: 40.0.0
    repository: https://traefik.github.io/charts
